### ISSUE TITLE
different value for <option>

### ISSUE THREAD

**Issue by djcamo** [sergiodlopes/jquery-flexdatalist#25]
your data list uses this syntax - `<option value="PHP">PHP</option>`

what if want to use - `<option value="123">PHP</option>` which is data from a database

this does not seem to work - i get back all records in the db

this is site, search by category (Golf Clubs - Courses) - http://barossalink.businesscatalyst.com/

**Comment by sergiodlopes** [comment]
Hi,

Not sure I understood your question.

If you get back all records from database and that's not what you want, you need to filter the results. The plugin sends the keyword on each AJAX request.

From what I saw, you're searching in the name and even though there's a ID property in JSON, you're not using it as the value.

Please explain what you're trying to do.

**Comment by djcamo** [comment]
if i search for Accommodation then this is your html

`<input type="hidden" placeholder="Search by Category" class="search-cat flexdatalist flexdatalist-set flexdatalist-selected" data-min-length="1" list="categories" name="CAT_Category" id="CAT_Category" value="Accommodation">`

`<input type="text" placeholder="Search by Category" class="search-cat flexdatalist-alias" data-min-length="1" id="CAT_Category-flexdatalist" autocomplete="off">`

I want the value of the hidden field to be 69934, which is the id in the db that the search uses

**Comment by djcamo** [comment]
worked it out - I added **valueProperty: 'value'** to the javascript

thanks all the same

**Comment by sergiodlopes** [comment]
Hi,

Glad you worked it out. I wasn't understanding what you needed, sorry.

Cheers!
Sérgio

**Comment by VladislavKim92** [comment]
Hi,
placeholder is not visible using flexdatalist
html:
<input type='text'  class='input-city' list='cities' placeholder='choose your city'>
js:
$('.input-city).flexdatalist({
   minLength: 1
})

**Comment by ROBMEYE** [comment]
Hi,

I have the same problem as djacamo, I use a datalist with different values like
<option value="123">PHP</option>
and I used the suggestion of djacomo regarding "valueProperty: 'value'" to get the value "123" back instead of the text "PHP".
But my problem is that I have to use muliple selections and if I add "valueProperty: 'value'" multiple selections are not working any more because then the search list is shown for a second selection but by  clicking on one of the entries nothing hapens and the selected second item is not shown in the input field, only the first one.

Is there any possibility/suggestion how I can realize a multiple selection with different values?

Thank you very much for your efforts!

Kind regards,
Robert.
