### ISSUE TITLE
Get data from url ajax

### ISSUE THREAD

**Issue by byinff** [sergiodlopes/jquery-flexdatalist#3]
Hi again,

How do i can get information from url via ajax and send parameters aditional ?

Thanks!

**Comment by sergiodlopes** [comment]
Hi,

Can you please give me an example of what you're trying to achieve?

Thanks!

**Comment by byinff** [comment]
My instance plugin of flexdatalist : 

$('#formMessage #data').flexdatalist({
	 minLength: 3,
	 selectionRequired : true,
	searchIn: 'name',
     	data:'www.domain.com/topic.php'
});

there any way to get data from a url via ajax ?

**Comment by sergiodlopes** [comment]
Get the data as you type it?

**Comment by byinff** [comment]
Instead of consulting the information from a json, would consult the information via ajax to the server and returns the information through a json. But the problem is that I need to send additional parameters.

**Comment by sergiodlopes** [comment]
I see.

Instead of `data:'www.domain.com/topic.php'` use  `url:'www.domain.com/topic.php'`. Using the `data` option, will download the remote data one time. While `url` will keep "asking" the remote server for the results.

At the moment (from the plugin) you can't send additional parameters on request. I'll implement that. :)

**Comment by sergiodlopes** [comment]
It's now possible to send additional parameters with the AJAX requests, along with other features!
