### ISSUE TITLE
Como alterar o valor do input programaticamente

### ISSUE THREAD

**Issue by cmpm72** [sergiodlopes/jquery-flexdatalist#89]
Depois de iniciado o flexdatalist altero o input text programaticamente e o flexdatalist não o considera.

Como posso alterar atualizar o valor no flexdatalist?

**Comment by sergiodlopes** [comment]
Hei,

Descarrega a v2.0.6, deverá ter esse problema resolvido.

----------------------------------------------------------------------

Check v2.0.6, should have the problem fixed.

Since the documentation is a bit poor at the moment about this subject, here's how you can get/set value by many ways:

### Set
`$('.flexdatalist').val('My new value');`
`$('.flexdatalist').flexdatalist('value', 'My new value');`
`$('.flexdatalist')[0].fvalue.set('My new value');`

### Get
As a string (even when it's supposed to be multiple values or JSON):
`$('.flexdatalist').val();`

As the expected format (CSV or JSON) (useful for further manipulating the input data):
`$('.flexdatalist').flexdatalist('value');`
If are expected multiple values, you'll get an simple array/object of values (CSV) or if `options.valueProperty` is set to `*`, you'll get the selected JSON object.

Or, you can get into the internal API:
`$('.flexdatalist')[0].fvalue.get();`
`get()` accepts one argument, true for getting value as a string

Cheers!
Sérgio
